services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gr8wTh50x
      POSTGRES_DB: clinicflow
    volumes:
      - proj_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: clinicflow_app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:gr8wTh50x@postgres:5432/clinicflow
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npm start"

# `pgadmin` added to manage the Postgres instance. Login with the email/password above.

volumes:
  proj_pgdata:
    external: true
  pgadmin_data:
    driver: local